backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "songs"
    label: "Songs"
    folder: "songs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }
